sudo: required
language: python
# Keep up to date with the tox.ini list
services:
  - docker
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3

install:
  - pip install pip-tools
  - pip-compile requirements.in
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - make docs
  - make test
after_success:
  - coveralls
